name: Deploy to Azure Function App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: 6.0.x
  PROJECT_PATH: App/App.csproj
  AZURE_FUNCTIONAPP_NAME: af-aad-func
  AZURE_RESOURCE_GROUP: af-aad-rg
  AZURE_LOCATION: uksouth

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
    - name: Checkout Code
      uses: actions/checkout@v3

      # Setup .NET Core SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
      # Install dependencies
    - name: Restore dependencies
      run: dotnet restore ${{env.PROJECT_PATH}}
    
      # Build
    - name: Build Project
      run: dotnet build --no-restore --verbosity normal ${{env.PROJECT_PATH}}
    
      # Publish artifacts
    - name: Publish artifacts
      run: dotnet publish --configuration Release --output ./publish

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Function App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: production
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        package: ./publish
        