name: Deploy to Azure Function App

on:
  push:
    branches: [ "main" ]
    path-ignore:
      - "**.md"
      - "**.yml"
      - ".github/**"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: 6.0.x
  PROJECT_PATH: src/App
  SOLUTION_PATH: src
  AZURE_FUNCTIONAPP_NAME: af-aad-func
  AZURE_RESOURCE_GROUP: af-aad-rg
  AZURE_LOCATION: uksouth

jobs:
  BuildOnLinux:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
    - name: Checkout Code
      uses: actions/checkout@v3

      # Setup .NET Core SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
      # Install dependencies
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.SOLUTION_PATH}}
    
      # Build
    - name: Build Project
      run: dotnet build --no-restore --verbosity normal 
      working-directory: ${{env.SOLUTION_PATH}}
    
      # Publish artifacts
    - name: Publish artifacts
      run: dotnet publish --configuration Release --output ./output
      working-directory: ${{env.PROJECT_PATH}}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.PROJECT_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} 
  
        